services:
  - type: web
    name: coinglass-webhook-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python webhook_server.py"
    envVars:
      - key: PORT
        value: 5000

  - type: worker
    name: coinglass-auto-alert
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
